# Generated by Django 4.2.30 on 2026-09-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plant_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='session_key',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
