# Generated by Django 4.2.30 on 2026-09-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_remove_plant_session_key_diagnosis_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='favorite_plants',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
