# Generated by Django 4.2.30 on 2026-09-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_userpreference_experience_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='language',
            field=models.CharField(default='en', max_length=20),
        ),
    ]
